name: shop
description: A sample command-line application.
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: '>=2.19.1 <3.0.0'

# dependencies:
#   path: ^1.8.0

dependencies:
  flutter:
    sdk: flutter
  lints: ^2.0.0
  test: ^1.21.0
  intl: ^0.18.0
  provider: ^6.0.5
  go_router: ^6.2.0
  flutter_masked_text2: ^0.9.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true